# Generated by Django 5.1.3 on 2024-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_remove_activitylog_user_activitylog_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('steps', 'Steps'), ('workout', 'Workout'), ('flexibility', 'Flexibility')], max_length=20),
        ),
    ]
