# Generated by Django 5.1.3 on 2024-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='profile',
        ),
    ]
