# Generated by Django 5.1.3 on 2024-12-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_goal_type'),
    ]

    operations = [
    ]
