# Generated by Django 5.1.3 on 2024-12-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20241202_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
    ]
